/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Sach;
import model.ListLoaiSach;
import model.LoaiSach;
import model.dsSach;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class QuanLySach extends javax.swing.JFrame {
    ListLoaiSach dsLoaiSP = new ListLoaiSach();
    dsSach listSach = new dsSach();
    SimpleDateFormat date_format = new SimpleDateFormat("yyyy");
    /**
     * Creates new form QuanLySach
     */
    public QuanLySach() {
        initComponents();
        
        // Hiển thị frame giữa màn hình
        setLocationRelativeTo(null);
        
        // Lấy dữ liệu của hộp tùy chọn
        getDataComboBox();
    }
    
    public void getDataComboBox(){
        DefaultComboBoxModel<LoaiSach> model = 
                (DefaultComboBoxModel) cboLoaiSach.getModel();
        
        for(LoaiSach loai : dsLoaiSP.getALLLoaiSach()){
            model.addElement(loai);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lbMaSach = new javax.swing.JLabel();
        lbTenSach = new javax.swing.JLabel();
        lbTacGia = new javax.swing.JLabel();
        lbLoaiSach = new javax.swing.JLabel();
        txtMaSach = new javax.swing.JTextField();
        txtTenSach = new javax.swing.JTextField();
        txtTacGia = new javax.swing.JTextField();
        cboLoaiSach = new javax.swing.JComboBox<>();
        lbNhaXuatBan = new javax.swing.JLabel();
        lbNamXuatBan = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        txtNhaXuatBan = new javax.swing.JTextField();
        txtNamXuatBan = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSach = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản lý sách");

        lbMaSach.setText("Mã sách");

        lbTenSach.setText("Tên sách");

        lbTacGia.setText("Tên tác giả");

        lbLoaiSach.setText("Loại sách");

        cboLoaiSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSachActionPerformed(evt);
            }
        });

        lbNhaXuatBan.setText("Nhà xuất bản");

        lbNamXuatBan.setText("Năm xuất bản");

        lbSoLuong.setText("Số lượng");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hinh/Add.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hinh/Edit.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hinh/Delete.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hinh/Search.png"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        TableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Tên tác giả", "Loại sách", "Nhà xuất bản", "Năm xuất bản", "Số lượng"
            }
        ));
        TableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableSach);

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hinh/Refresh.png"))); // NOI18N
        btnRefresh.setText("Làm mới");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTenSach)
                            .addComponent(txtMaSach)
                            .addComponent(txtTacGia)
                            .addComponent(cboLoaiSach, 0, 189, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbNhaXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(lbNamXuatBan, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(lbSoLuong, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSoLuong)
                                    .addComponent(txtNamXuatBan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnRefresh))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMaSach)
                            .addComponent(txtMaSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenSach)
                            .addComponent(txtTenSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTacGia)
                            .addComponent(txtTacGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNhaXuatBan)
                            .addComponent(txtNhaXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNamXuatBan)
                            .addComponent(txtNamXuatBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSoLuong)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLoaiSach)
                    .addComponent(cboLoaiSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        
        if(!checkValidForm()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
            
        }
        else{
            try {
                Sach s = getModelSach();
                System.out.println("=>"+s.toString());
                if(listSach.edit(s)>0){
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    fillData();
                }
            } catch (ParseException ex) {
                System.out.println("Error"+ex.toString());
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    // Làm mới ô nhập
    public void resetForm(){
        txtMaSach.setText("");
        txtTenSach.setText("");
        txtTacGia.setText("");
        txtNhaXuatBan.setText("");
        txtNamXuatBan.setText("");
        txtSoLuong.setText("");
        cboLoaiSach.setSelectedIndex(0);
    }
    
    // Kiểm tra những ô chưa nhập
    public boolean checkValidForm(){
        if(txtMaSach.getText().isEmpty()
                || txtTenSach.getText().isEmpty()
                || txtTacGia.getText().isEmpty()
                || txtNhaXuatBan.getText().isEmpty()
                || txtNamXuatBan.getText().isEmpty()
                || txtSoLuong.getText().isEmpty()) {
            return false;
        }
        return true;
    }
    
    public Sach getModelSach() throws ParseException{
        Sach s = new Sach();
        s.setMaSach(txtMaSach.getText().trim());
        s.setTenSach(txtTenSach.getText().trim());
        s.setTenTacGia(txtTacGia.getText().trim());
        s.setNhaXB(txtNhaXuatBan.getText().trim());
        s.setSoLuong(Integer.parseInt(txtSoLuong.getText().trim()));
        s.setLoaiSach((LoaiSach) cboLoaiSach.getSelectedItem());
        s.setNamXB(date_format.parse(txtNamXuatBan.getText().trim()));
        return s;
    }
    
    public void fillData(){
        DefaultTableModel tbModel = 
                (DefaultTableModel) TableSach.getModel();
        tbModel.setRowCount(0); // Clear table
        for(Sach s : listSach.getAllSach()){
            Object[] rowData = new Object[7];
            rowData[0] = s.getMaSach();
            rowData[1] = s.getTenSach();
            rowData[2] = s.getTenTacGia();
            rowData[3] = s.getLoaiSach();
            rowData[4] = s.getNhaXB();
            rowData[5] = date_format.format(s.getNamXB());
            rowData[6] = s.getSoLuong();
            tbModel.addRow(rowData);
        }
    }
    
    
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
        
        if(!checkValidForm()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đầy đủ thông tin");
            
        }
        else{
            try {
                Sach s = getModelSach();
                System.out.println("=>"+s.toString());
                if(listSach.add(s)>0){
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    fillData();
                }
            } catch (ParseException ex) {
                System.out.println("Error"+ex.toString());
            }
        }
//        resetForm();
    }//GEN-LAST:event_btnThemActionPerformed

    private void cboLoaiSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiSachActionPerformed

    private void TableSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSachMouseClicked
        // TODO add your handling code here:
        int rowID = TableSach.rowAtPoint(evt.getPoint());
        Sach s = listSach.getSachAtPoint(rowID);
        if(s == null){
            return;
        }
        setModel(s);
        
    }//GEN-LAST:event_TableSachMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnRefreshActionPerformed
    
    public void setModel(Sach s){
        txtMaSach.setText(s.getMaSach());
        txtTenSach.setText(s.getTenSach());
        txtTacGia.setText(s.getTenTacGia());
        txtNhaXuatBan.setText(s.getNhaXB());
        txtNamXuatBan.setText(date_format.format(s.getNamXB()));
        txtSoLuong.setText(s.getSoLuong()+"");
        cboLoaiSach.setSelectedItem(s.getLoaiSach());
    }
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        if(txtMaSach.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã sách cần tìm");
        }
        else{
            Sach s = listSach.findByID(txtMaSach.getText().trim());
            if(s != null){
                JOptionPane.showMessageDialog(this, "Đã tìm thấy sách có mã là "+txtMaSach.getText());
                // fill form
                setModel(s);
            }else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy có mã là "+txtMaSach.getText());
            }
                
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if(txtMaSach.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mã sách cần xóa");
        }
        else{
            if(listSach.del(txtMaSach.getText().trim())>0){
                JOptionPane.showMessageDialog(this, "Đã xóa thành công");
                fillData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Không tìm thấy mã sách");
            }
        }
            
    }//GEN-LAST:event_btnXoaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new QuanLySach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSach;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoaiSach;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbLoaiSach;
    private javax.swing.JLabel lbMaSach;
    private javax.swing.JLabel lbNamXuatBan;
    private javax.swing.JLabel lbNhaXuatBan;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTacGia;
    private javax.swing.JLabel lbTenSach;
    private javax.swing.JTextField txtMaSach;
    private javax.swing.JTextField txtNamXuatBan;
    private javax.swing.JTextField txtNhaXuatBan;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTacGia;
    private javax.swing.JTextField txtTenSach;
    // End of variables declaration//GEN-END:variables

    private void depose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
